version: '3.8'

services:
  ezinventory-web:
    container_name: ezinventory-web
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      # Proxy & SSL Settings
      - VIRTUAL_HOST=api.aamakonana.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.aamakonana.com
      - LETSENCRYPT_EMAIL=bibhab.dev@gmail.com

      # Shared Database Connection
      # Points to the 'global-db' container on the 'web_gateway' network
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}

    ports:
      - 8000:8000
    
    volumes:
      - .:/app
    
    networks:
      - web_gateway

    command: >
      gunicorn backend.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --worker-class gevent
      --worker-connections 1000
      --timeout 120
      --access-logfile -
      --error-logfile -

networks:
  web_gateway:
    external: true

